const nameDatabase = {
    russia: {
        male: {
            first: ["Ivan", "Dmitri", "Sergei", "Alexei", "Mikhail", "Nikolai", "Andrei", "Vladimir", "Yuri", "Pavel",
                    "Anatoly", "Boris", "Viktor", "Gennady", "Konstantin", "Leonid", "Oleg", "Roman", "Stanislav", "Valery",
                    "Arkady", "Denis", "Fyodor", "Grigory", "Igor", "Kirill", "Lev", "Maxim", "Nikita", "Timur",
                    "Vadim", "Yakov", "Zakhar", "Artem", "Bogdan", "Daniil", "Egor", "Filipp", "Georgy", "Ilya",
                    "Jaroslav", "Klim", "Leon", "Matvey", "Naum", "Oskar", "Pyotr", "Rodion", "Semyon", "Taras",
                    "Ustin", "Vsevolod", "Yaroslav", "Afanasy", "Benedikt", "Vasily", "Gavril", "Demyan", "Yevgeny", "Zinovy",
                    "Innokenty", "Yosif", "Kuzma", "Luka", "Miron", "Nestor", "Ostap", "Panteley", "Ruslan", "Savely",
                    "Tikhon", "Ulyan", "Foma", "Khariton", "Efim", "Yury", "Zakhar", "Arseny", "Boris", "Vladislav"],
            last: ["Ivanov", "Smirnov", "Kuznetsov", "Popov", "Vasiliev", "Petrov", "Sokolov", "Mikhailov", "Fedorov", "Morozov",
                   "Volkov", "Novikov", "Lebedev", "Kozlov", "Stepanov", "Orlov", "Sobolev", "Baranov", "Polyakov", "Vinogradov",
                   "Semyonov", "Pavlov", "Golubev", "Vinogradov", "Bogdanov", "Vorobyov", "Fyodorov", "Zhukov", "Tarasov", "Belov",
                   "Komarov", "Krylov", "Isaev", "Guryev", "Yefimov", "Zaitsev", "Kalinin", "Makarenko", "Osipov", "Romanov",
                   "Savchenko", "Timofeev", "Frolov", "Chernov", "Shcherbakov", "Egorov", "Karpov", "Kovalev", "Kuzmin", "Maksimov",
                   "Melnikov", "Nikitin", "Ponomarev", "Ryabov", "Sorokin", "Titov", "Ushakov", "Filippov", "Chernyshev", "Shubin",
                   "Yakovlev", "Belyaev", "Gromov", "Davydov", "Zhuravlev", "Zuev", "Ignatov", "Kotov", "Lazarev", "Makarov",
                   "Naumov", "Ovchinnikov", "Petukhov", "Rogov", "Sidorov", "Tkachev", "Fomin", "Khokhlov", "Yudin", "Biryukov"]
        },
        female: {
            first: ["Anna", "Maria", "Elena", "Olga", "Tatiana", "Natalia", "Irina", "Svetlana", "Yulia", "Ekaterina",
                    "Anastasia", "Daria", "Galina", "Inna", "Ksenia", "Larisa", "Margarita", "Nina", "Oksana", "Polina",
                    "Raisa", "Sofia", "Tamara", "Valentina", "Zoya", "Albina", "Bella", "Vera", "Galia", "Diana",
                    "Zhanna", "Zinaida", "Karina", "Lidia", "Lyubov", "Marina", "Nadezhda", "Rimma", "Snezhana", "Taisiya",
                    "Uliana", "Faina", "Yana", "Alla", "Viktoria", "Gertruda", "Dina", "Evgenia", "Zoya", "Ivanna",
                    "Kira", "Lilia", "Lyudmila", "Milana", "Nika", "Olesya", "Raisa", "Svetlana", "Toma", "Ulyana",
                    "Feodora", "Kharitina", "Elizaveta", "Yaroslava", "Zina", "Agnessa", "Bogdana", "Varvara", "Glafira", "Darina",
                    "Yevdokia", "Zoya", "Inessa", "Yulianna", "Klara", "Lubomila", "Miroslava", "Nonna", "Olimpiada", "Pelageya",
                    "Rostislava", "Stanislava", "Tosya", "Fekla", "Ksenofonta", "Elmira", "Yadviga", "Zlata"],
            last: ["Ivanova", "Smirnova", "Kuznetsova", "Popova", "Vasilieva", "Petrova", "Sokolova", "Mikhailova", "Fedorova", "Morozova",
                   "Volkova", "Novikova", "Lebedeva", "Kozlova", "Stepanova", "Orlova", "Soboleva", "Baranova", "Polyakova", "Vinogradova",
                   "Semyonova", "Pavlova", "Golubeva", "Vinogradova", "Bogdanova", "Vorobyova", "Fyodorova", "Zhukova", "Tarasova", "Belova",
                   "Komarova", "Krylova", "Isaeva", "Guryeva", "Yefimova", "Zaitseva", "Kalinina", "Makarenko", "Osipova", "Romanova",
                   "Savchenko", "Timofeeva", "Frolova", "Chernova", "Shcherbakova", "Egorova", "Karpova", "Kovaleva", "Kuzmina", "Maksimova",
                   "Melnikova", "Nikitina", "Ponomareva", "Ryabova", "Sorokina", "Titova", "Ushakova", "Filippova", "Chernysheva", "Shubina",
                   "Yakovleva", "Belyaeva", "Gromova", "Davydova", "Zhuravleva", "Zueva", "Ignatova", "Kotova", "Lazareva", "Makarova",
                   "Naumova", "Ovchinnikova", "Petukhova", "Rogova", "Sidorova", "Tkacheva", "Fomina", "Khokhlova", "Yudina", "Biryukova"]
        }
    },
    china: {
        male: {
            first: ["Wei", "Ming", "Jie", "Lei", "Tao", "Feng", "Jian", "Bin", "Hao", "Yang",
                    "Qiang", "Jun", "Bo", "Dong", "Guang", "Hong", "Kang", "Long", "Peng", "Qing",
                    "Rui", "Sheng", "Tian", "Wei", "Xin", "Yong", "Zhi", "An", "Bao", "Chao",
                    "Da", "En", "Fu", "Gang", "Hai", "Jin", "Kai", "Liang", "Min", "Ning",
                    "Qi", "Rong", "Shan", "Teng", "Wei", "Xiong", "Yan", "Zheng", "Ao", "Bing",
                    "Chen", "De", "Er", "Fang", "Gen", "Heng", "Ji", "Kun", "Lin", "Mao",
                    "Nan", "Ou", "Ping", "Quan", "Ren", "Shi", "Tong", "Wen", "Xiang", "Yao",
                    "Ze", "Chang", "Ding", "Fei", "Guo", "Hua", "Jia", "Ke", "Li", "Meng",
                    "Nian", "Pei", "Qiu", "Song", "Tang", "Wu", "Xue", "Yi", "Zhu", "Cheng"],
            last: ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Zhao", "Huang", "Zhou", "Wu",
                   "Xu", "Sun", "Ma", "Zhu", "Hu", "Guo", "Lin", "He", "Gao", "Luo",
                   "Zheng", "Liang", "Xie", "Song", "Tang", "Han", "Feng", "Deng", "Cao", "Peng",
                   "Pan", "Jiang", "Yu", "Yuan", "Qian", "Cai", "Lu", "Du", "Wei", "Jia",
                   "Zhong", "Tian", "Dong", "Fan", "Fang", "Shi", "Bai", "Wan", "Xiao", "Su",
                   "Kong", "Shen", "Jin", "Zou", "Bao", "An", "Yin", "Qiu", "Meng", "Gong",
                   "Yan", "Lai", "Wen", "Niu", "Shi", "Gou", "Leng", "Ran", "Dang", "Shan",
                   "Ruan", "Lan", "Kuang", "Geng", "Ji", "Chu", "Niu", "Mi", "Jing", "Hua",
                   "Lian", "Qu", "Mu", "Xi", "Ruan", "Che", "Tong", "Ning", "Gan", "Jing"]
        },
        female: {
            first: ["Mei", "Ling", "Xia", "Yan", "Li", "Hui", "Fang", "Ying", "Juan", "Na",
                    "Qing", "Rong", "Shu", "Ting", "Wen", "Xiu", "Yu", "Zhen", "Ai", "Bing",
                    "Chun", "Dan", "E", "Fen", "Guo", "Hong", "Jia", "Ke", "Lan", "Min",
                    "Ning", "Ping", "Qi", "Rui", "Shan", "Tao", "Wei", "Xin", "Yue", "Zhi",
                    "An", "Bao", "Chen", "Dai", "Er", "Fei", "Ge", "Hai", "Ji", "Kai",
                    "Le", "Ming", "Nian", "Ou", "Pei", "Qiu", "Ran", "Si", "Tong", "Wu",
                    "Xiang", "Yan", "Zhu", "Chang", "Ding", "En", "Fang", "Gao", "Hua", "Jin",
                    "Kang", "Li", "Meng", "Nai", "Pang", "Qian", "Rou", "Shi", "Tang", "Wei",
                    "Xue", "Yi", "Zhao", "Cheng", "Dong", "Fang", "Gu", "Huan", "Jie", "Kun",
                    "Lian", "Mei", "Nuan", "Ping", "Qiong", "Rong", "Shuang", "Ting", "Wan", "Xia"],
            last: ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Zhao", "Huang", "Zhou", "Wu",
                   "Xu", "Sun", "Ma", "Zhu", "Hu", "Guo", "Lin", "He", "Gao", "Luo",
                   "Zheng", "Liang", "Xie", "Song", "Tang", "Han", "Feng", "Deng", "Cao", "Peng",
                   "Pan", "Jiang", "Yu", "Yuan", "Qian", "Cai", "Lu", "Du", "Wei", "Jia",
                   "Zhong", "Tian", "Dong", "Fan", "Fang", "Shi", "Bai", "Wan", "Xiao", "Su",
                   "Kong", "Shen", "Jin", "Zou", "Bao", "An", "Yin", "Qiu", "Meng", "Gong",
                   "Yan", "Lai", "Wen", "Niu", "Shi", "Gou", "Leng", "Ran", "Dang", "Shan",
                   "Ruan", "Lan", "Kuang", "Geng", "Ji", "Chu", "Niu", "Mi", "Jing", "Hua",
                   "Lian", "Qu", "Mu", "Xi", "Ruan", "Che", "Tong", "Ning", "Gan", "Jing"]
        }
    },
    japan: {
        male: {
            first: ["Haruto", "Riku", "Yuto", "Sota", "Ren", "Kaito", "Daiki", "Ryota", "Yuki", "Shota",
                    "Sho", "Taiga", "Kai", "Sora", "Rui", "Hayato", "Kosei", "Tsubasa", "Kazuki", "Hinata",
                    "Kento", "Takumi", "Yuma", "Ryusei", "Kotaro", "Shun", "Keigo", "Reo", "Eito", "Fuma",
                    "Itsuki", "Jun", "Kyo", "Masato", "Naoki", "Osamu", "Ryo", "Shin", "Takeru", "Yamato",
                    "Aoi", "Daichi", "Hiro", "Issei", "Joji", "Kazuya", "Makoto", "Noboru", "Riku", "Satoshi",
                    "Tatsuya", "Yuya", "Akira", "Daisuke", "Hikaru", "Ichiro", "Jiro", "Katsumi", "Mamoru", "Norihiro",
                    "Rikuto", "Seiji", "Tadashi", "Yoshio", "Asahi", "Eiji", "Hajime", "Iori", "Junichi", "Kenji",
                    "Masaru", "Norio", "Ryosuke", "Shingo", "Toshiro", "Yasuo", "Akio", "Eisuke", "Hideki", "Isao",
                    "Jin", "Kohei", "Minoru", "Naoto", "Ryota", "Shinji", "Tomohiro", "Yutaka", "Arata", "Fumio"],
            last: ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Yoshida",
                   "Yamada", "Sasaki", "Yamaguchi", "Matsumoto", "Inoue", "Kimura", "Hayashi", "Shimizu", "Yamazaki", "Mori",
                   "Abe", "Ikeda", "Hashimoto", "Ishikawa", "Yamashita", "Ogawa", "Ishii", "Hasegawa", "Fujita", "Goto",
                   "Okada", "Kondo", "Maeda", "Fujii", "Endo", "Aoki", "Nishimura", "Fukuda", "Ota", "Miura",
                   "Fujiwara", "Okamoto", "Matsuda", "Nakagawa", "Nakano", "Harada", "Ono", "Tamura", "Takeuchi", "Kaneko",
                   "Wada", "Nakayama", "Ishida", "Ueda", "Morita", "Hara", "Shibata", "Sakai", "Kudo", "Yokoyama",
                   "Miyazaki", "Miyamoto", "Uchida", "Takada", "Ando", "Taniguchi", "Ohno", "Maruyama", "Imai", "Takasaki",
                   "Kikuchi", "Sano", "Mochizuki", "Yamanaka", "Nishiyama", "Kojima", "Sugimoto", "Masuda", "Koike", "Narita",
                   "Hirano", "Otsuka", "Chiba", "Kubo", "Murata", "Iwasaki", "Sugiyama", "Kinoshita", "Noguchi", "Matsui"]
        },
        female: {
            first: ["Himari", "Mei", "Yui", "Rin", "Sakura", "Aoi", "Koharu", "Hina", "Mio", "Ichika",
                    "Akari", "Riko", "Mao", "Yuna", "Miyu", "Saki", "Nozomi", "Airi", "Mana", "Rina",
                    "Nana", "Kanna", "Ayane", "Shiori", "Nanami", "Mizuki", "Haruka", "Yua", "Kotone", "Sumire",
                    "Honoka", "Suzu", "Miu", "Yuzuki", "Rena", "Karin", "Momo", "Sana", "Tsubaki", "Yurina",
                    "Ami", "Ema", "Hana", "Kaho", "Mai", "Natsuki", "Rio", "Shiho", "Tomoka", "Yume",
                    "Asuka", "Emi", "Haru", "Kaede", "Mika", "Nao", "Risa", "Shino", "Tomo", "Yuina",
                    "Aya", "Eri", "Hinata", "Kanon", "Minami", "Nayuta", "Rion", "Sena", "Tsugumi", "Yuki",
                    "Azusa", "Fuka", "Hotaru", "Karen", "Misaki", "Noa", "Ruri", "Serena", "Uta", "Yoshino",
                    "Chiharu", "Fumika", "Iroha", "Kokoro", "Mitsuki", "Nonoka", "Satsuki", "Tina", "Wakana", "Yuna"],
            last: ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Yoshida",
                   "Yamada", "Sasaki", "Yamaguchi", "Matsumoto", "Inoue", "Kimura", "Hayashi", "Shimizu", "Yamazaki", "Mori",
                   "Abe", "Ikeda", "Hashimoto", "Ishikawa", "Yamashita", "Ogawa", "Ishii", "Hasegawa", "Fujita", "Goto",
                   "Okada", "Kondo", "Maeda", "Fujii", "Endo", "Aoki", "Nishimura", "Fukuda", "Ota", "Miura",
                   "Fujiwara", "Okamoto", "Matsuda", "Nakagawa", "Nakano", "Harada", "Ono", "Tamura", "Takeuchi", "Kaneko",
                   "Wada", "Nakayama", "Ishida", "Ueda", "Morita", "Hara", "Shibata", "Sakai", "Kudo", "Yokoyama",
                   "Miyazaki", "Miyamoto", "Uchida", "Takada", "Ando", "Taniguchi", "Ohno", "Maruyama", "Imai", "Takasaki",
                   "Kikuchi", "Sano", "Mochizuki", "Yamanaka", "Nishiyama", "Kojima", "Sugimoto", "Masuda", "Koike", "Narita",
                   "Hirano", "Otsuka", "Chiba", "Kubo", "Murata", "Iwasaki", "Sugiyama", "Kinoshita", "Noguchi", "Matsui"]
        }
    },
    korea: {
        male: {
            first: ["Min-jun", "Seo-jun", "Ji-ho", "Do-yun", "Eun-woo", "Si-woo", "Ji-hoon", "Hyun-woo", "Jun-seo", "Ye-jun",
                    "Dae-hyun", "Seung-hyun", "Tae-hyun", "Yoon-seo", "Jae-hyun", "Hae-jun", "Ki-hoon", "Min-ki", "Sang-hoon", "Woo-jin",
                    "Chan-ho", "Dong-hyun", "Geon-woo", "Hwan", "In-seo", "Joon-ho", "Kyung-ho", "Min-soo", "Seok-hoon", "Won-jun",
                    "Baek-ho", "Chul-soo", "Dong-min", "Gi-hun", "Ho-joon", "Jin-woo", "Kwang-min", "Myung-ho", "Seung-woo", "Young-jae",
                    "Byung-ho", "Chun-ho", "Eun-jae", "Hae-won", "Jae-sung", "Jin-ho", "Kyung-soo", "Min-hyuk", "Seo-yoon", "Yoon-ho",
                    "Chang-min", "Dae-jung", "Gun-woo", "Hoon", "Jae-won", "Ji-seok", "Kyu-hyun", "Min-seok", "Seung-min", "Woo-sung",
                    "Chae-hoon", "Dong-wook", "Han-bin", "Hyun-jun", "Jae-hyuk", "Ji-woong", "Min-gyu", "Seo-hyun", "Tae-min", "Yong-jun",
                    "Cheol-min", "Dong-jun", "Hee-jun", "Hyun-soo", "Jae-min", "Jin-seok", "Min-woo", "Seung-jae", "Tae-yang", "Young-ho"],
            last: ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim",
                   "Han", "Shin", "Song", "Yu", "Kwak", "Ahn", "Seo", "Oh", "Hwang", "Moon",
                   "Baek", "Cha", "Do", "Go", "Ha", "Im", "Jeon", "Koo", "Na", "Ryu",
                   "Son", "Woo", "Yang", "Bae", "Chae", "Chung", "Gang", "Hong", "Joo", "Kwon",
                   "Nam", "Paik", "Seok", "Sim", "Won", "Yeo", "Bang", "Byun", "Chon", "Eom",
                   "Gwon", "Hahn", "Hyun", "Jeong", "Kang", "Ko", "Maeng", "No", "Park", "Roh",
                   "Seong", "Suh", "Um", "Yoo", "Bong", "Chang", "Cheon", "Doh", "Gong", "Huh",
                   "Jang", "Kang", "Kye", "Min", "Noh", "Pyo", "Sa", "Sohn", "Tak", "Youn",
                   "Bak", "Chin", "Choo", "Guk", "Hahm", "Ho", "Jee", "Kang", "Kyung", "Myung"]
        },
        female: {
            first: ["Ji-ah", "Seo-yeon", "Ji-yoo", "Ha-eun", "Seo-yun", "Ji-woo", "Eun-ji", "Ye-eun", "Ji-min", "Soo-ah",
                    "Da-bin", "Seo-hyun", "Ji-hye", "Hae-rin", "Seo-jin", "Ji-soo", "Eun-bi", "Yeon-woo", "Ji-eun", "Soo-min",
                    "Bo-ram", "Seung-hee", "Ji-won", "Hana", "Seo-ah", "Ji-young", "Eun-ha", "Ye-seul", "Ji-seon", "Soo-ji",
                    "Chae-won", "Seo-yoon", "Ji-yeon", "Hae-won", "Seo-ri", "Ji-hyun", "Eun-seo", "Ye-rim", "Ji-sook", "Soo-yeon",
                    "Da-som", "Seul-gi", "Ji-ae", "Hae-in", "Seo-woo", "Ji-na", "Eun-sol", "Yeon-joo", "Ji-young", "Soo-kyung",
                    "Ga-young", "Seung-ah", "Ji-woo", "Hae-jin", "Seo-hui", "Ji-sun", "Eun-young", "Yeon-hee", "Ji-yoon", "Soo-hyun",
                    "Bit-na", "Seung-yeon", "Ji-ri", "Hae-mi", "Seo-mi", "Ji-hwa", "Eun-jung", "Yeon-kyung", "Ji-young", "Soo-jin",
                    "Cho-won", "Seung-mi", "Ji-kyung", "Hae-na", "Seo-na", "Ji-eun", "Eun-kyung", "Yeon-ah", "Ji-hae", "Soo-jeong"],
            last: ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim",
                   "Han", "Shin", "Song", "Yu", "Kwak", "Ahn", "Seo", "Oh", "Hwang", "Moon",
                   "Baek", "Cha", "Do", "Go", "Ha", "Im", "Jeon", "Koo", "Na", "Ryu",
                   "Son", "Woo", "Yang", "Bae", "Chae", "Chung", "Gang", "Hong", "Joo", "Kwon",
                   "Nam", "Paik", "Seok", "Sim", "Won", "Yeo", "Bang", "Byun", "Chon", "Eom",
                   "Gwon", "Hahn", "Hyun", "Jeong", "Kang", "Ko", "Maeng", "No", "Park", "Roh",
                   "Seong", "Suh", "Um", "Yoo", "Bong", "Chang", "Cheon", "Doh", "Gong", "Huh",
                   "Jang", "Kang", "Kye", "Min", "Noh", "Pyo", "Sa", "Sohn", "Tak", "Youn",
                   "Bak", "Chin", "Choo", "Guk", "Hahm", "Ho", "Jee", "Kang", "Kyung", "Myung"]
        }
    }
};

const nativeScriptDatabase = {
    russia: {
        male: {
            first: ["Иван", "Дмитрий", "Сергей", "Алексей", "Михаил", "Николай", "Андрей", "Владимир", "Юрий", "Павел",
                    "Анатолий", "Борис", "Виктор", "Геннадий", "Константин", "Леонид", "Олег", "Роман", "Станислав", "Валерий",
                    "Аркадий", "Денис", "Фёдор", "Григорий", "Игорь", "Кирилл", "Лев", "Максим", "Никита", "Тимур",
                    "Вадим", "Яков", "Захар", "Артём", "Богдан", "Даниил", "Егор", "Филипп", "Георгий", "Илья",
                    "Ярослав", "Клим", "Леон", "Матвей", "Наум", "Оскар", "Пётр", "Родион", "Семён", "Тарас",
                    "Устин", "Всеволод", "Ярослав", "Афанасий", "Бенедикт", "Василий", "Гавриил", "Демьян", "Евгений", "Зиновий",
                    "Иннокентий", "Иосиф", "Кузьма", "Лука", "Мирон", "Нестор", "Остап", "Пантелей", "Руслан", "Савелий",
                    "Тихон", "Ульян", "Фома", "Харитон", "Ефим", "Юрий", "Захар", "Арсений", "Борис", "Владислав"],
            last: ["Иванов", "Смирнов", "Кузнецов", "Попов", "Васильев", "Петров", "Соколов", "Михайлов", "Фёдоров", "Морозов",
                   "Волков", "Новиков", "Лебедев", "Козлов", "Степанов", "Орлов", "Соболев", "Баранов", "Поляков", "Виноградов",
                   "Семёнов", "Павлов", "Голубев", "Виноградов", "Богданов", "Воробьёв", "Фёдоров", "Жуков", "Тарасов", "Белов",
                   "Комаров", "Крылов", "Исаев", "Гурьев", "Ефимов", "Зайцев", "Калинин", "Макаренко", "Осипов", "Романов",
                   "Савченко", "Тимофеев", "Фролов", "Чернов", "Щербаков", "Егоров", "Карпов", "Ковалёв", "Кузьмин", "Максимов",
                   "Мельников", "Никитин", "Пономарёв", "Рябов", "Сорокин", "Титов", "Ушаков", "Филиппов", "Чернышёв", "Шубин",
                   "Яковлев", "Беляев", "Громов", "Давыдов", "Журавлёв", "Зуев", "Игнатов", "Котов", "Лазарев", "Макаров",
                   "Наумов", "Овчинников", "Петухов", "Рогов", "Сидоров", "Ткачёв", "Фомин", "Хохлов", "Юдин", "Бирюков"]
        },
        female: {
            first: ["Анна", "Мария", "Елена", "Ольга", "Татьяна", "Наталья", "Ирина", "Светлана", "Юлия", "Екатерина",
                    "Анастасия", "Дарья", "Галина", "Инна", "Ксения", "Лариса", "Маргарита", "Нина", "Оксана", "Полина",
                    "Раиса", "София", "Тамара", "Валентина", "Зоя", "Альбина", "Белла", "Вера", "Галия", "Диана",
                    "Жанна", "Зинаида", "Карина", "Лидия", "Любовь", "Марина", "Надежда", "Римма", "Снежана", "Таисия",
                    "Ульяна", "Фаина", "Яна", "Алла", "Виктория", "Гертруда", "Дина", "Евгения", "Зоя", "Иванна",
                    "Кира", "Лилия", "Людмила", "Милана", "Ника", "Олеся", "Раиса", "Светлана", "Тома", "Ульяна",
                    "Феодора", "Харитина", "Елизавета", "Ярослава", "Зина", "Агнесса", "Богдана", "Варвара", "Глафира", "Дарьяна",
                    "Евдокия", "Зоя", "Инесса", "Юлианна", "Клара", "Любомила", "Мирослава", "Нонна", "Олимпиада", "Пелагея",
                    "Ростислава", "Станислава", "Тося", "Фёкла", "Ксенофонтa", "Эльмира", "Ядвига", "Злата"],
            last: ["Иванова", "Смирнова", "Кузнецова", "Попова", "Васильева", "Петрова", "Соколова", "Михайлова", "Фёдорова", "Морозова",
                   "Волкова", "Новикова", "Лебедева", "Козлова", "Степанова", "Орлова", "Соболева", "Баранова", "Полякова", "Виноградова",
                   "Семёнова", "Павлова", "Голубева", "Виноградова", "Богданова", "Воробьёва", "Фёдорова", "Жукова", "Тарасова", "Белова",
                   "Комарова", "Крылова", "Исаева", "Гурьева", "Ефимова", "Зайцева", "Калинина", "Макаренко", "Осипова", "Романова",
                   "Савченко", "Тимофеева", "Фролова", "Чернова", "Щербакова", "Егорова", "Карпова", "Ковалёва", "Кузьмина", "Максимова",
                   "Мельникова", "Никитина", "Пономарёва", "Рябова", "Сорокина", "Титова", "Ушакова", "Филиппова", "Чернышёва", "Шубина",
                   "Яковлева", "Беляева", "Громова", "Давыдова", "Журавлёва", "Зуева", "Игнатова", "Котова", "Лазарева", "Макарова",
                   "Наумова", "Овчинникова", "Петухова", "Рогова", "Сидорова", "Ткачёва", "Фомина", "Хохлова", "Юдина", "Бирюкова"]
        }
    },
    china: {
        male: {
            first: ["伟", "明", "杰", "磊", "涛", "峰", "建", "斌", "浩", "洋",
                    "强", "军", "波", "东", "光", "宏", "康", "龙", "鹏", "清",
                    "瑞", "生", "天", "伟", "鑫", "勇", "志", "安", "宝", "超",
                    "达", "恩", "福", "刚", "海", "金", "凯", "亮", "敏", "宁",
                    "奇", "荣", "山", "腾", "伟", "雄", "岩", "正", "傲", "冰",
                    "晨", "德", "尔", "方", "根", "恒", "吉", "坤", "林", "茂",
                    "南", "欧", "平", "泉", "仁", "石", "桐", "文", "祥", "尧",
                    "泽", "昌", "定", "飞", "国", "华", "佳", "可", "力", "梦",
                    "年", "培", "秋", "松", "唐", "武", "学", "毅", "柱", "成"],
            last: ["王", "李", "张", "刘", "陈", "杨", "赵", "黄", "周", "吴",
                   "徐", "孙", "马", "朱", "胡", "郭", "林", "何", "高", "罗",
                   "郑", "梁", "谢", "宋", "唐", "韩", "冯", "邓", "曹", "彭",
                   "潘", "姜", "余", "袁", "钱", "蔡", "陆", "杜", "魏", "贾",
                   "钟", "田", "董", "范", "方", "石", "白", "万", "萧", "苏",
                   "孔", "沈", "金", "邹", "包", "安", "尹", "邱", "孟", "龚",
                   "严", "赖", "文", "牛", "史", "苟", "冷", "冉", "党", "单",
                   "阮", "蓝", "邝", "耿", "纪", "褚", "牛", "米", "景", "花",
                   "廉", "曲", "穆", "席", "阮", "车", "童", "宁", "甘", "景"]
        },
        female: {
            first: ["梅", "玲", "霞", "艳", "丽", "慧", "芳", "英", "娟", "娜",
                    "晴", "蓉", "淑", "婷", "雯", "秀", "玉", "珍", "爱", "冰",
                    "春", "丹", "娥", "芬", "国", "红", "佳", "可", "兰", "敏",
                    "宁", "萍", "琪", "瑞", "珊", "桃", "薇", "欣", "月", "芝",
                    "安", "宝", "晨", "黛", "尔", "菲", "歌", "海", "吉", "开",
                    "乐", "明", "年", "欧", "佩", "秋", "然", "思", "桐", "武",
                    "香", "燕", "珠", "昌", "丁", "恩", "芳", "高", "华", "金",
                    "康", "丽", "梦", "奈", "庞", "倩", "柔", "诗", "棠", "薇",
                    "雪", "怡", "昭", "成", "东", "芳", "谷", "欢", "洁", "坤",
                    "莲", "美", "暖", "平", "琼", "蓉", "霜", "婷", "婉", "夏"],
            last: ["王", "李", "张", "刘", "陈", "杨", "赵", "黄", "周", "吴",
                   "徐", "孙", "马", "朱", "胡", "郭", "林", "何", "高", "罗",
                   "郑", "梁", "谢", "宋", "唐", "韩", "冯", "邓", "曹", "彭",
                   "潘", "姜", "余", "袁", "钱", "蔡", "陆", "杜", "魏", "贾",
                   "钟", "田", "董", "范", "方", "石", "白", "万", "萧", "苏",
                   "孔", "沈", "金", "邹", "包", "安", "尹", "邱", "孟", "龚",
                   "严", "赖", "文", "牛", "史", "苟", "冷", "冉", "党", "单",
                   "阮", "蓝", "邝", "耿", "纪", "褚", "牛", "米", "景", "花",
                   "廉", "曲", "穆", "席", "阮", "车", "童", "宁", "甘", "景"]
        }
    },
    japan: {
        male: {
            first: ["蓮", "湊", "陽翔", "蒼", "樹", "律", "暖", "颯", "陽向", "碧",
                    "翔", "大河", "海", "空", "瑠偉", "隼人", "恒星", "翼", "和樹", "陽向",
                    "健人", "匠", "悠真", "流星", "虎太郎", "瞬", "慶吾", "玲央", "瑛斗", "風真",
                    "樹", "淳", "京", "正人", "直樹", "修", "亮", "真", "武", "大和",
                    "碧", "大地", "宏", "一成", "譲二", "和也", "誠", "昇", "陸", "智",
                    "達也", "裕也", "明", "大輔", "光", "一郎", "次郎", "克己", "守", "徳弘",
                    "陸斗", "清二", "忠", "良夫", "朝日", "英二", "元", "伊織", "順一", "健二",
                    "勝", "典夫", "昇", "剛", "翔太", "慎吾", "俊宏", "保", "亮", "篤",
                    "新", "英輔", "英樹", "勲", "仁", "浩平", "稔", "直人", "涼太", "信",
                    "新", "文雄", "秀樹", "勲", "悟", "浩", "雅", "拓哉", "豊", "新"]
            // (Note: Continued with similar expansion as Latin script names)
        },
        female: {
            first: ["陽葵", "凛", "結菜", "芽依", "咲良", "葵", "莉子", "紬", "澪", "結愛",
                    "朱里", "莉子", "真央", "優奈", "美優", "咲希", "望", "愛莉", "真奈", "莉奈",
                    "菜々", "栞那", "彩音", "七海", "南", "美月", "遥", "優羽", "琴音", "菫",
                    "穂香", "涼", "美羽", "優月", "玲奈", "花蓮", "桃", "紗奈", "椿", "由梨奈",
                    "亜美", "恵麻", "花", "佳穂", "舞", "夏樹", "莉緒", "詩穂", "朋香", "夢",
                    "明日香", "恵美", "春", "楓", "美香", "奈緒", "里桜", "詩乃", "朋", "優菜",
                    "あや", "恵理", "陽", "花音", "美咲", "菜月", "莉緒", "志乃", "知佳", "優衣菜",
                    "あずさ", "風香", "陽", "可憐", "美桜", "菜穂", "莉子", "詩音", "つぐみ", "優希",
                    "あやね", "文", "ひなた", "花恋", "美晴", "菜摘", "莉緒", "星奈", "うた", "佳乃",
                    "千春", "史織", "ほたる", "花恋", "美咲", "菜乃", "莉子", "星羅", "ティナ", "和香奈"]
            // (Note: Continued with similar expansion as Latin script names)
        },
        last: ["佐藤", "鈴木", "高橋", "田中", "渡辺", "伊藤", "山本", "中村", "小林", "吉田",
               "山田", "佐々木", "山口", "松本", "井上", "木村", "林", "清水", "山崎", "森",
               "阿部", "池田", "橋本", "石川", "山下", "小川", "石井", "長谷川", "藤田", "後藤",
               "岡田", "近藤", "前田", "藤井", "遠藤", "青木", "西村", "福田", "太田", "三浦",
               "藤原", "岡本", "松田", "中川", "中野", "原田", "小野", "田村", "竹内", "金子",
               "和田", "中山", "石田", "上田", "森田", "原", "柴田", "酒井", "工藤", "横山",
               "宮崎", "宮本", "内田", "高田", "安藤", "谷口", "大野", "丸山", "今井", "高木",
               "菊地", "佐野", "望月", "山中", "西田", "小島", "杉本", "増田", "小池", "成田",
               "平野", "大塚", "千葉", "久保", "村田", "岩崎", "杉山", "木下", "野口", "松井"]
    },
    korea: {
        male: {
            first: ["민준", "서준", "도윤", "은우", "시우", "지호", "이안", "하준", "유준", "선우",
                    "대현", "승현", "태현", "윤서", "재현", "해준", "기훈", "민기", "상훈", "우진",
                    "찬호", "동현", "건우", "환", "인서", "준호", "경호", "민수", "석훈", "원준",
                    "백호", "철수", "동민", "기훈", "호준", "진우", "광민", "명호", "승우", "영재",
                    "병호", "춘호", "은재", "해원", "재성", "진호", "경수", "민혁", "서윤", "윤호",
                    "창민", "대중", "건우", "훈", "재원", "지석", "규현", "민석", "승민", "우성",
                    "채훈", "동욱", "한빈", "현준", "재혁", "지웅", "민규", "서현", "태민", "용준",
                    "철민", "동준", "희준", "현수", "재민", "진석", "민우", "승재", "태양", "영호"],
            last: ["김", "이", "박", "최", "정", "강", "조", "윤", "장", "임",
                   "한", "신", "송", "유", "곽", "안", "서", "오", "황", "문",
                   "백", "차", "도", "고", "하", "임", "전", "구", "나", "류",
                   "손", "우", "양", "배", "채", "정", "강", "홍", "주", "권",
                   "남", "백", "석", "심", "원", "여", "방", "변", "천", "엄",
                   "권", "한", "현", "정", "강", "고", "맹", "노", "박", "노",
                   "성", "서", "엄", "유", "봉", "창", "천", "도", "공", "허",
                   "장", "강", "계", "민", "노", "표", "사", "손", "탁", "윤",
                   "박", "진", "추", "국", "함", "호", "지", "강", "경", "명"]
        },
        female: {
            first: ["지안", "서아", "하윤", "서윤", "아윤", "지유", "아린", "이서", "지아", "나은",
                    "다빈", "서현", "지혜", "해린", "서진", "지수", "은비", "연우", "지은", "수민",
                    "보람", "승희", "지원", "하나", "서아", "지영", "은하", "예슬", "지선", "수지",
                    "채원", "서윤", "지연", "해원", "서리", "지현", "은서", "예림", "지숙", "수연",
                    "다솜", "슬기", "지애", "해인", "서우", "지나", "은솔", "연주", "지영", "수경",
                    "가영", "승아", "지우", "해진", "서희", "지선", "은영", "연희", "지윤", "수현",
                    "빛나", "승연", "지리", "해미", "서미", "지화", "은정", "연경", "지영", "수진",
                    "초원", "승미", "지경", "해나", "서나", "지은", "은경", "연아", "지해", "수정"],
            last: ["김", "이", "박", "최", "정", "강", "조", "윤", "장", "임",
                   "한", "신", "송", "유", "곽", "안", "서", "오", "황", "문",
                   "백", "차", "도", "고", "하", "임", "전", "구", "나", "류",
                   "손", "우", "양", "배", "채", "정", "강", "홍", "주", "권",
                   "남", "백", "석", "심", "원", "여", "방", "변", "천", "엄",
                   "권", "한", "현", "정", "강", "고", "맹", "노", "박", "노",
                   "성", "서", "엄", "유", "봉", "창", "천", "도", "공", "허",
                   "장", "강", "계", "민", "노", "표", "사", "손", "탁", "윤",
                   "박", "진", "추", "국", "함", "호", "지", "강", "경", "명"]
        }
    }
};